repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.275
    hooks:
      - id: ruff
# Temporarily disabled due to crash, probably caused by us having to use HA stubs which are out of date?
# See https://github.com/nathanmarlor/foxess_modbus/actions/runs/12610946302/job/35146070831?pr=720
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.5.1
#    hooks:
#      - id: mypy
#        # These are duplicated from requirements.txt
#        additional_dependencies:
#          [
#            homeassistant-stubs==2024.12.5,
#            types-python-slugify==8.0.0.2,
#            voluptuous-stubs==0.1.1,
#          ]
